{
 "title": "EstacionMeteorologica",
 "time": { "from": "2022-12-01T14:03:41.646Z", "to": "2022-12-01T14:05:49.590Z" },
 "panels": [
  {
   "title": "Estacion Meteorologica 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatura Actual",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "temperatura_valor_1" }
     ]
    },
    {
     "title": "Temperatura Historico",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      { "expr": "temperatura_valor_1" }
     ]
    },
    {
     "title": "Velocidad del Viento",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "velocidad_valor_1" }
     ]
    },
    {
     "title": "Humedad Actual",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "humedad_valor_1" }
     ]
    },
    {
     "title": "Humedad Historico",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 7 },
     "yaxes": [
      { "format": "humidity" }
     ],
     "targets": [
      { "expr": "humedad_valor_2" }
     ]
    },
    {
     "title": "L / m²",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 19, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "valor_lluvia_1" }
     ]
    },
    {
     "title": "Preseion Historico",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pressurepa" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "valor_presion_2" }
     ]
    }
   ]
  },
  {
   "title": "Estacion Meteorologica 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatura Actual",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "temperatura_valor_2" }
     ]
    },
    {
     "title": "Temperatura Historico",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      { "expr": "temperatura_valor_1" }
     ]
    },
    {
     "title": "Velocidad del Viento",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "velocidad_valor_2" }
     ]
    },
    {
     "title": "Humedad Actual",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "humedad_valor_2" }
     ]
    },
    {
     "title": "Humedad Historico",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "humidity" }
     ],
     "targets": [
      { "expr": "humedad_valor_1" }
     ]
    },
    {
     "title": "L / m²",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "valor_lluvia_1" }
     ]
    },
    {
     "title": "Preseion Historico",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "pressurepa" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "valor_presion_2" }
     ]
    }
   ]
  }
 ]
}