{
 "title": "EstacionMeteorologica",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Estacion Meteorologica 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura Actual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "temperature_in_celsius_1" }
   ]
  },
  {
   "title": "Velocidad del Viento",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "wind_speed_1" }
   ]
  },
  {
   "title": "Temperatura Historico",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_in_celsius_1" }
   ]
  },
  {
   "title": "Humedad Actual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "humidity_1" }
   ]
  },
  {
   "title": "L / m²",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rain_precipitation_1" }
   ]
  },
  {
   "title": "Humedad Historico",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "humidity_1" }
   ]
  },
  {
   "title": "Direccion ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wind_direction_1" }
   ]
  },
  {
   "title": "Nivel luz",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "light_level_1" }
   ]
  },
  {
   "title": "Presion Historico",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "yaxes": [
    { "format": "pressurepa" }
   ],
   "targets": [
    { "expr": "atmospheric_pressure_1" }
   ]
  },
  {
   "title": "Temperaruta media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temperature_in_celsius_1" }
   ]
  },
  {
   "title": "L / m² media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rain_precipitation_1" }
   ]
  },
  {
   "title": "Humedad media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "humidity_1" }
   ]
  },
  {
   "title": "Velocidad del Viento media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wind_speed_1" }
   ]
  },
  { "title": "Estacion Meteorologica 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Temperatura Actual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temperature_in_celsius_2" }
   ]
  },
  {
   "title": "Velocidad del Viento",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "wind_speed_2" }
   ]
  },
  {
   "title": "Temperatura Historico",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_in_celsius_2" }
   ]
  },
  {
   "title": "Humedad Actual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "humidity_2" }
   ]
  },
  {
   "title": "L / m²",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rain_precipitation_2" }
   ]
  },
  {
   "title": "Humedad Historico",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "humidity_2" }
   ]
  },
  {
   "title": "Direccion ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wind_direction_2" }
   ]
  },
  {
   "title": "Nivel luz",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "light_level_2" }
   ]
  },
  {
   "title": "Presion Historico",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "yaxes": [
    { "format": "pressurepa" }
   ],
   "targets": [
    { "expr": "atmospheric_pressure_2" }
   ]
  },
  {
   "title": "Temperaruta media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temperature_in_celsius_0" }
   ]
  },
  {
   "title": "L / m² media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rain_precipitation_2" }
   ]
  },
  {
   "title": "Humedad media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "humidity_2" }
   ]
  },
  {
   "title": "Velocidad del Viento media",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wind_speed_2" }
   ]
  }
 ]
}