route:
  receiver: 'mail'
  repeat_interval: 24h
  group_by: [ alertname ]

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'yourmailhost.com:465'
        auth_username: 'yourmail@yourmailhost.com'
        auth_password: "your mail password"
        from: 'yourmail@yourmailhost.com'
        to: 'someonesmail@yourmailhost.com'
        require_tls: false