apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      name: python-application
      namespace: monitoring
      labels:
        app: python-application
    spec:
      containers:
        - name: python-application
          image: python-application:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
