apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: Estacion meteorologica
      rules:
      - alert: Temperatura muy baja
        expr: valor_criptomonedas > 3
        for: 1m
        labels:
          severity: page
        annotations:
          summary: Temperatura muy baja

  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    scrape_configs:
      - job_name: my-application
        honor_labels: true
        static_configs:
        - targets: ['flask:5000']

      

 